spring.application.name=backend

# Configuração para VS Code online (Codespaces)
server.address=0.0.0.0
server.port=8080

# Desabilitar Spring Boot Docker Compose quando rodando em container
spring.docker.compose.enabled=false

# Desabilitar Spring Boot Docker Compose quando rodando em container
spring.docker.compose.enabled=false
